### ISSUE TITLE
Create a new image to be used for paper wallets.

### ISSUE THREAD

**Issue by detroitpro** [akroma-project/akroma-wallet-web#1]
## Description
Create a new image to be used for paper wallets.

#### Acceptance Criteria
Attach an updated image that replaces the current logo and text.

#### Bounty/Reward
50 AKA

#### Details/Assets/Extra Info

**Old image**
![https://wallet.akroma.io/images/print-sidebar.png](https://wallet.akroma.io/images/print-sidebar.png)

**Comment by StephenKoller** [comment]
![print-sidebar](https://user-images.githubusercontent.com/1561673/36059305-d306c128-0e03-11e8-885c-29816fbb2c92.png)
How does this look?
