### ISSUE TITLE
Add support for Hardware Wallets

### ISSUE THREAD

**Issue by mkrufky** [akroma-project/akroma-wallet-web#9]
Trezor supports ChainId's > 255 in their upcoming firmware update.  Let's add support for Akroma!

- [x] trezor-mcu chainId > 255 fix: https://github.com/trezor/trezor-mcu/pull/381

- [x] SLIP-0044: 200625: https://github.com/satoshilabs/slips/pull/326

- [x] trezor-mcu akroma support: https://github.com/trezor/trezor-mcu/pull/387

- [x] trezor-common akroma support: https://github.com/trezor/trezor-common/pull/177

- [x] modified web wallet for testing: http://mkrufky.github.io/etherwallet

- [x] ledger official akroma support: https://github.com/LedgerHQ/blue-app-eth/pull/19

- [x] modified official akroma web wallet:  deployed

We will hold back on enabling the trezor support on the akroma web wallet until the next firmware is officially released.  Ledger is usable today by building and installing my Akroma app for the Ledger.

**Comment by detroitpro** [comment]
@mkrufky does https://github.com/akroma-project/akroma-wallet-web/pull/10 complete the last check mark?

**Comment by mkrufky** [comment]
@detroitpro I just renamed the issue to reflect LEDGER support, rather than Trezor support.   Now that it's about LEDGER support, yes, when #10 gets deployed, we can check that last box and close this ticket.   When the new TREZOR firmware comes out, it will be an additional one-liner to enable that in the web wallet.   We can handle that when the time comes.

**Comment by detroitpro** [comment]
I'll work on deploying it tomorrow, want to make sure I don't deploy and then run out (I'll be AFK the rest of the night)
